/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollapseItem: typeof import('./src/components/Pages/ChartItemSetting/CollapseItem.vue')['default']
    DialogContent: typeof import('./src/components/Plugins/DialogContent/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputGroup: typeof import('element-plus/es')['ElInputGroup']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    GlobalSetting: typeof import('./src/components/Pages/ChartItemSetting/GlobalSetting.vue')['default']
    GlobalSettingPosition: typeof import('./src/components/Pages/ChartItemSetting/GlobalSettingPosition.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KhMenu: typeof import('./src/components/element/khMenu/index.vue')['default']
    KhMenuItem: typeof import('./src/components/element/khMenuItem/index.vue')['default']
    MessageContent: typeof import('./src/components/Plugins/MessageContent/index.vue')['default']
    NameSetting: typeof import('./src/components/Pages/ChartItemSetting/NameSetting.vue')['default']
    PositionSetting: typeof import('./src/components/Pages/ChartItemSetting/PositionSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./src/components/Pages/ChartItemSetting/SettingItem.vue')['default']
    SettingItemBox: typeof import('./src/components/Pages/ChartItemSetting/SettingItemBox.vue')['default']
    SizeSetting: typeof import('./src/components/Pages/ChartItemSetting/SizeSetting.vue')['default']
    StylesSetting: typeof import('./src/components/Pages/ChartItemSetting/StylesSetting.vue')['default']
  }
}
